routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes - Test for @Mindvalley
|--------------------------------------------------------------------------
|
*/

// Pages ------------------------------------------------------------------
Route::get('/', 'PageController@index');
Route::get('/detail/{id}', 'PageController@getDetails');
Route::get('/stories', 'PageController@getStories')->name('get.stories');

// Article Resource ------------------------------------------------------
Route::resource('articles', 'ArticleController');
Route::get('featured', 'ArticleController@getRandomFeatured');
Route::get('/articles/tags/{tag}', 'ArticleController@getTagArticles')->name('tag.articles');

// Auth ------------------------------------------------------------------
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

resources/views/pages/create.blade.php
@extends('layouts.medium')

@section('extra-css')
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css">
@endsection

@section('content')
    <div class="container mx-auto">
        <div class="flex mb-4">
            <div class="w-full text-grey-darker px-12 py-2 m-2 mt-6">
                @if (count($errors) > 0)
                  <div class="bg-red border-l-4 border-red text-red p-4 mb-5" role="alert">
                     <p class="font-normal text-white">Please fix errors</p>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                  </div>
                @endif

              <form method="POST" action="{{ route('articles.store') }}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" enctype="multipart/form-data">
                @csrf
                <div class="mb-4">
                  <label class="block text-grey-darker text-sm font-bold mb-2" for="title">
                    Title
                  </label>
                  <input name="title" required class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" id="username" value="{{ old('title') }}" type="text" placeholder="Title">
                  @error('title')
                    <p class="text-red text-xs italic">{{ $message }}</p>
                  @enderror
                </div>
                <div class="mb-4">
                  <label class="block text-grey-darker text-sm font-bold mb-2" for="excerpt">
                    Excerpt
                  </label>
                  <textarea required placeholder="Short Content" name="short_content" class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" id="short_content" cols="3" rows="2">{{ old('short_content') }}</textarea>
                  @error('short_content')
                    <p class="text-red text-xs italic">{{ $message }}</p>
                  @enderror
                </div>
                <div class="mb-4">
                  <label class="block text-grey-darker text-sm font-bold mb-2" for="email">
                    Description
                  </label>
                  <textarea required name="long_content" placeholder="Description" class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" id="long_content" cols="3" rows="5">{{ old('long_content') }}</textarea>
                  @error('long_content')
                    <p class="text-red text-xs italic">{{ $message }}</p>
                  @enderror
                </div>
                <div class="mb-4">
                    <label class="block text-grey-darker text-sm font-bold mb-3" for="email">
                      Tags
                    </label>
                    <select name="tags[]" class="select2-multi block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" multiple="multiple">
                        @foreach( $tags as $tag )
                          <option value="{{ $tag->id }}">{{ $tag->title }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-4">
                    <input type="checkbox" name="featured_article" id="featured_article"> <span class="text-grey-darker text-sm font-bold">Featured</span>
                  </div>
                <div class="mb-4">
                    <label class="block text-grey-darker text-sm font-bold mb-2" for="featured">
                      Featured Image
                    </label>
                    <input type="file" name="featured_image" id="featured_image">
                </div>
                <div class="flex items-center justify-between">
                  <button class="bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Publish
                  </button>
                </div>
              </form>
              <p class="text-center text-grey text-xs">
                ©2019 Blog Test @ Mindvalley. All rights reserved.
              </p>
            </div>
        </div>
    </div>
@endsection

@section('extra-js')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
  <script type="text/javascript">
		$(".select2-multi").select2();
	</script>
@endsection

resources/views/pages/dashboard.blade.php
@extends('layouts.medium')

@section('content')
    <div class="container mx-auto">
        <div class="w-2/3 max-w-sm p-8 animated fadeIn">
              <div class="p-2">
                  <div class="border shadow">
                      <div class="border-t-4 -mt-1 border-green w-2/4 flex flex-wrap justify-center pb-8 bg-green-lightest">
                          <h3 class="w-full p-4 text-grey-darkest">Hi, {{ '@'.auth()->user()->name }}</h3>
                          <a href="{{ route('articles.create') }}" class="bg-green-dark hover:bg-green-light text-white font-semibold py-4 px-4 border border-blue hover:border-transparent rounded no-underline">
                              New Article
                          </a>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </div>
@endsection

resources/views/pages/detail.blade.php
@extends('layouts.medium')

@section('content')
    <div class="container mx-auto">
        {{-- Article Detail --}}
        <blog-detail></blog-detail>
    </div>
@endsection

resources/views/pages/edit.blade.php
@extends('layouts.medium')

@section('extra-css')
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css">
@endsection

@section('content')
    <div class="container mx-auto">
        <div class="flex mb-4">
            <div class="w-full text-grey-darker px-12 py-2 m-2 mt-6">
                @if(count($errors->all()) > 0)
                  <div class="bg-red border-l-4 border-red text-white p-4 mb-5" role="alert">
                    <p class="font-normal text-white">Please fix errors</p>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                  </div>
                @endif

              <form method="POST" action="{{ route('articles.update', $article->id) }}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="mb-4">
                  <label class="block text-grey-darker text-sm font-bold mb-2" for="title">
                    Title
                  </label>
                  <input name="title" required class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" id="username" value="{{ $article->title }}" type="text" placeholder="Title">
                  @error('title')
                    <p class="text-red text-xs italic">{{ $message }}</p>
                  @enderror
                </div>
                <div class="mb-4">
                  <label class="block text-grey-darker text-sm font-bold mb-2" for="excerpt">
                    Excerpt
                  </label>
                  <textarea required placeholder="Short Content" name="short_content" class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" id="short_content" cols="3" rows="2">{{ $article->short_content }}</textarea>
                  @error('short_content')
                    <p class="text-red text-xs italic">{{ $message }}</p>
                  @enderror
                </div>
                <div class="mb-4">
                  <label class="block text-grey-darker text-sm font-bold mb-2" for="email">
                    Description
                  </label>
                  <textarea required name="long_content" placeholder="Description" class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" id="long_content" cols="3" rows="5">{{ $article->long_content }}</textarea>
                  @error('long_content')
                    <p class="text-red text-xs italic">{{ $message }}</p>
                  @enderror
                </div>
                <div class="mb-4">
                    <label class="block text-grey-darker text-sm font-bold mb-3" for="email">
                      Tags
                    </label>
                    <select name="tags[]" id="tags" class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500 select2-multi" multiple="multiple">
                        @foreach( \App\Tag::all() as $tag )
                          <option value="{{ $tag->id }}">{{ $tag->title }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="mb-4">
                    <input type="checkbox" name="featured_article" id="featured_article"> <span class="text-grey-darker text-sm font-bold">Featured</span>
                  </div>
                <div class="mb-4">
                    <img class="h-32 w-32 rounded-full mx-auto" src="{{ $article->featured_image }}">
                    <label class="block text-grey-darker text-sm font-bold mb-2" for="featured">
                      Featured Image
                    </label>
                    <input type="file" name="featured_image" id="featured_image">
                </div>
                <div class="flex items-center justify-between">
                  <button class="bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Update
                  </button>
                </div>
              </form>
              <p class="text-center text-grey text-xs">
                ©2019 Blog Test @ Mindvalley. All rights reserved.
              </p>
            </div>
        </div>
    </div>
@endsection

@section('extra-js')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
  <script type="text/javascript">
		// $(".select2-multi").select2();
    $("#tags").select2();
	</script>
@endsection

resources/views/pages/index.blade.php
@extends('layouts.medium')

@section('content')
<div class="container mx-auto">
    <div class="flex flex-wrap mx-2">

        <!-- Articles List Content -->
        <div class="w-full lg:w-3/4 px-4 mb-10">
            <blog-list></blog-list>
        </div>

        <!-- Sidebar -->
        <div class="w-full lg:w-1/4 px-4 mb-8">
            <div class="px-4 mb-8">
                <h2 class="mb-3">Popular on Medium</h2>
                <div class="border-b-2 border-grey-light mb-1"></div>
                <featured-articles></featured-articles>
            </div>
        </div>

    </div>
</div>
@endsection

resources/views/pages/login.blade.php
@extends('layouts.medium')

@section('content')
    <div class="container mx-auto">
        <div class="flex mb-4">
            <div class="w-full text-grey-darker px-12 py-2 m-2 mt-10">
              <form method="POST" action="{{ route('login') }}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
                @csrf
                <div class="mb-4">
                  <label class="block text-grey-darker text-sm font-bold mb-2" for="username">
                    Email
                  </label>
                  <input name="email" required class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" id="username" type="text" placeholder="Username">
                  @error('email')
                    <p class="text-red text-xs italic">{{ $message }}</p>
                  @enderror
                </div>
                <div class="mb-6">
                  <label class="block text-grey-darker text-sm font-bold mb-2" for="password">
                    Password
                  </label>
                  <input name="password" required class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" id="password" type="password" placeholder="******************">
                  @error('password')
                    <p class="text-red text-xs italic">{{ $message }}</p>
                  @enderror
                </div>
                <div class="flex items-center justify-between">
                  <button class="bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Sign In
                  </button>
                  {{-- <a class="inline-block align-baseline font-bold text-sm text-blue hover:text-blue-darker" href="#">
                    Forgot Password?
                  </a> --}}
                </div>
              </form>
              <p class="text-center text-grey text-xs">
                ©2019 Blog Test @ Mindvalley. All rights reserved.
              </p>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/register.blade.php
@extends('layouts.medium')

@section('content')
    <div class="container mx-auto">
        <div class="flex mb-4">
            <div class="w-full text-grey-darker px-12 py-2 m-2 mt-10">
              <form method="POST" action="{{ route('register') }}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
                @csrf
                <div class="mb-4">
                  <label class="block text-grey-darker text-sm font-bold mb-2" for="name">
                    Name
                  </label>
                  <input name="name" required class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" id="username" value="{{ old('name') }}" type="text" placeholder="Username">
                  @error('name')
                    <p class="text-red text-xs italic">{{ $message }}</p>
                  @enderror
                </div>
                <div class="mb-4">
                  <label class="block text-grey-darker text-sm font-bold mb-2" for="email">
                    Email
                  </label>
                  <input name="email" required class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" value="{{ old('email') }}" id="username" type="email" placeholder="Email">
                  @error('email')
                    <p class="text-red text-xs italic">{{ $message }}</p>
                  @enderror
                </div>
                <div class="mb-6">
                  <label class="block text-grey-darker text-sm font-bold mb-2" for="password">
                    Password
                  </label>
                  <input name="password" required class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" id="password" type="password" placeholder="******************">
                  @error('password')
                    <p class="text-red text-xs italic">{{ $message }}</p>
                  @enderror
                </div>
                <div class="mb-6">
                  <label class="block text-grey-darker text-sm font-bold mb-2" for="password">
                    Confirm Password
                  </label>
                  <input name="password_confirmation" required class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline" id="password" type="password" placeholder="******************">
                </div>
                <div class="flex items-center justify-between">
                  <button class="bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Sign Up
                  </button>
                  {{-- <a class="inline-block align-baseline font-bold text-sm text-blue hover:text-blue-darker" href="#">
                    Forgot Password?
                  </a> --}}
                </div>
              </form>
              <p class="text-center text-grey text-xs">
                ©2019 Blog Test @ Mindvalley. All rights reserved.
              </p>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/stories.blade.php
@extends('layouts.medium')

@section('content')
    <div class="container flex mx-auto">
        <div class="w-full px-6 animated fadeIn">
            @if(session('success'))
              <div class="items-center bg-blue text-white text-sm font-bold px-4 py-3" role="alert">
                <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z"/></svg>
                <p>{{ session('success') }}</p>
              </div>
            @endif
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Title</th>
                  <th scope="col">Excerpt</th>
                  <th scope="col">Tags</th>
                  <th scope="col">Author</th>
                  <th scope="col">Created</th>
                  <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
                @foreach($articles as $key => $article)
                <tr>
                  <th scope="row">{{ $key + 1 }}</th>
                  <td>{{ $article->title }}</td>
                  <td>{{ $article->short_content }}</td>
                  <td>@foreach($article->tags as $tag) <span>{{ $tag->title }}</span> @endforeach</td>
                  <td>{{ $article->author->name }}</td>
                  <td>{{ $article->created_at->diffForHumans() }}</td>
                  <td>
                    <a href="{{ route('articles.edit', $article->id) }}" class="bg-blue hover:bg-blue text-white font-semibold py-2 px-4 rounded-full">Edit</a>
                  </td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
      </div>
    </div>
@endsection

resources/views/pages/tag-articles.blade.php
@extends('layouts.medium')

@section('content')
<div class="container mx-auto">
    <div class="flex flex-wrap mx-2">
        <!-- Articles List Content -->
        <div class="w-full lg:w-3/4 px-4 mb-10">
            @php $tag = \App\Tag::find(Request::segment(3)); @endphp
            <h3 class="mb-3 px-6 font-bold text-lg text-grey-darkest no-underline">Tags : {{ ucfirst($tag->title) }}</h3>
            <tag-articles></tag-articles>
        </div>

        <!-- Sidebar -->
        <div class="w-full lg:w-1/4 px-4 mb-8">
            <div class="px-4 mb-8">
                <h2 class="mb-3">Popular on Medium</h2>
                <div class="border-b-2 border-grey-light mb-2"></div>
                <featured-articles></featured-articles>
            </div>
        </div>

    </div>
</div>
@endsection